Strip sensor names off the device name prefix; better error handling
id628/flic2hass pull request #6
Opened 2023-08-19 06:08 UTC by mikevostrikov

- Fixes #3
- Eliminates the need to restart the module in Flic Hub SDK when the MQTT server is not available for a minute. Previous behaviour - this error was reported: flic hub fatal error: uncaught: 'cannot push beyond allocated stack' (Flic Hub Firmware: 3.0.12) - see https://community.flic.io/topic/18257/cannot-push-beyond-allocated-stack-fatal-error

2023-08-19 17:50 UTC, id628 approved these changes
Thank you!

2023-08-19 17:50 UTC, id628 approved these changes

2023-08-19 18:08 UTC, id628 requested changes
How does this actually address the bug?

Would you consider adding some code for LWT?

2023-08-19 21:16 UTC, mikevostrikov commented
> How does this actually address the bug?

As for #3 - I believe the current guidelines https://developers.home-assistant.io/docs/core/entity/#has_entity_name-true-mandatory-for-new-integrations prescribe that entity names should not start with the name of the device:
"**The entity's name property** only identifies the data point represented by the entity, and **should not include the name of the device** or the type of the entity."

As we use _button name_ as _device name_
![image](https://github.com/id628/flic2hass/assets/11011125/669a4077-0400-4ad7-9c0e-e1020fce185c)
I assumed that removing the _button name_ from the _sensor name_ might help. Hence I introduce the changes similar to this one:
![image](https://github.com/id628/flic2hass/assets/11011125/e245df72-7ef0-4cc8-8a36-6fdf9079190f)
After introducing the change I am not getting the warning in Home Assistant anymore.


As for the https://community.flic.io/topic/18257/cannot-push-beyond-allocated-stack-fatal-error the root cause seems to be in the Flic firmware itself. The suggested change is a workaround. In the existing implementation, it looks like every "error-reconnect" cycle
![image](https://github.com/id628/flic2hass/assets/11011125/ca43fefd-c205-43b9-9afe-b06fecc70ffd)
utilizes some stack space. After around 40 "error-reconnect" cycles it overflows with the fatal error in the log and Flic Hub stops sending events to MQTT. For some reason, the Flic Hub module is not getting restarted either even if this feature is enabled for the module:
![image](https://github.com/id628/flic2hass/assets/11011125/dcce8a08-2e24-49a6-9108-8fcde8826387)
The suggested change is to throw an error on MQTT 'error' event forcing the Flic Hub module to crash and restart fresh instead of going into the "error-reconnect" cycle.

> Would you consider adding some code for LWT?

Sorry, please clarify - I am not sure if I understand what is this question about. Did I miss something important as part of this change? I did not find mentions of LWT in the existing code..

Thank you!

2023-08-22 22:53 UTC, id628 approved these changes

2023-08-22 22:54 UTC, id628 approved these changes

2023-08-22 22:55 UTC, merged